In [ ]:
 from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Project(Housing)/BostonHousing.csv')
df.dropna()
df.head(10)

      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO  LSTAT  MEDV  CAT. MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3   4.98  24.0          0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8   9.14  21.6          0
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8   4.03  34.7          1
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7   2.94  33.4          1
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7   5.33  36.2          1
5  0.02985   0.0   2.18     0  0.458  ...  222     18.7   5.21  28.7          0
6  0.08829  12.5   7.87     0  0.524  ...  311     15.2  12.43  22.9          0
7  0.14455  12.5   7.87     0  0.524  ...  311     15.2  19.15  27.1          0
8  0.21124  12.5   7.87     0  0.524  ...  311     15.2  29.93  16.5          0
9  0.17004  12.5   7.87     0  0.524  ...  311     15.2  17.10  18.9          0

[10 rows x 14 columns]

In [ ]:
X = df.drop("CAT. MEDV" , axis = 1)
y = df["CAT. MEDV"]
X
y

0      0
1      0
2      1
3      1
4      1
      ..
501    0
502    0
503    0
504    0
505    0
Name: CAT. MEDV, Length: 506, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# xây model
model = Sequential()
model.add(Dense(128, input_shape=(13,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error', optimizer='adam')
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 128)            │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,161 (47.50 KB)

 Trainable params: 12,161 (47.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
history = model.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.1892
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0909
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0539
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0363
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0246
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0143
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0184
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0097
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0096
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0051
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0078
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0061
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0048
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0043
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0066
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0054
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0032
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0053
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0043
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0067
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0034
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0052
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0027
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0025
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0029
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0026
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0017
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0015
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0034
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0024
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0013
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0030
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0040
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0020
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0030
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0015
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0015
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5862e-04
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7918e-04
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0018
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0012
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0018
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0059
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0046
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0025
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0027
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.3929e-04
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.6970e-04
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0017
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.5581e-04
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.7349e-04
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6529e-04
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.1005e-04
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.7287e-04
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.3008e-04
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.6851e-04
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4469e-04
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.3036e-04
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9119e-04
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.3298e-04
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7247e-04
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.7528e-04
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5612e-04
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9854e-04
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0152e-04
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.3432e-04
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.4925e-04
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8818e-04
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.4882e-04
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.4304e-04
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0241e-04
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.2395e-04
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.3289e-04
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.7989e-04
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8378e-04
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2529e-04
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.3304e-04
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.5033e-04
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6982e-04
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1013e-04
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0156e-04
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.9003e-05
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.3691e-05
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0611e-04
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2032e-04
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5965e-05
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2991e-04
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2733e-04
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7215e-05
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.9146e-05
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1099e-05
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0286e-04
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2534e-04
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0147e-04
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.8853e-05
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0627e-04
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2582e-05
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2364e-04
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.0370e-05
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.5108e-05

In [ ]:
mean_squared_error(y_test, model.predict(X_test))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step

0.010176701471209526

In [ ]:
y_pred = model.predict(X_test)
y_pred

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

array([[8.45658997e-06],
       [9.93063986e-01],
       [1.17232113e-10],
       [5.19529983e-08],
       [4.31433000e-06],
       [4.44219665e-07],
       [9.15387801e-08],
       [4.43032444e-10],
       [7.11152052e-06],
       [2.07672883e-07],
       [4.75561421e-08],
       [1.14959380e-06],
       [3.38406858e-10],
       [2.31738704e-06],
       [3.97469968e-08],
       [5.10807931e-02],
       [4.97154362e-09],
       [1.40081258e-09],
       [9.99999523e-01],
       [2.26196994e-06],
       [5.22022492e-06],
       [1.27912745e-01],
       [7.88972568e-11],
       [3.51080143e-06],
       [2.22637505e-06],
       [9.80134800e-08],
       [1.58517736e-07],
       [4.68180087e-06],
       [2.48567090e-07],
       [7.53948200e-07],
       [1.11641248e-06],
       [2.57989232e-05],
       [5.37049300e-06],
       [1.28107844e-04],
       [1.02805893e-06],
       [1.69748921e-06],
       [9.97839630e-01],
       [5.26743058e-08],
       [2.01886160e-05],
       [2.27855764e-07],
       [4.16099681e-07],
       [1.05889305e-01],
       [9.99999642e-01],
       [4.95792518e-10],
       [3.94109691e-07],
       [1.51455004e-06],
       [1.75729639e-10],
       [6.48321475e-07],
       [8.93202832e-06],
       [6.53249372e-05],
       [1.54014333e-06],
       [9.98731911e-01],
       [6.40490860e-09],
       [8.11768346e-04],
       [9.99964416e-01],
       [1.13049042e-04],
       [1.42816898e-05],
       [3.23140100e-02],
       [1.31101899e-06],
       [1.07330749e-08],
       [7.16101145e-04],
       [9.99745905e-01],
       [4.63067181e-02],
       [9.89166509e-08],
       [1.56037077e-05],
       [4.42378179e-09],
       [1.15377827e-06],
       [5.37131336e-06],
       [6.88923776e-01],
       [3.51846609e-07],
       [5.12627674e-09],
       [5.53519756e-04],
       [1.53893325e-07],
       [2.52520915e-09],
       [6.61228796e-07],
       [1.81448478e-09],
       [6.15049601e-07],
       [9.99999285e-01],
       [2.28162136e-07],
       [2.05165339e-13],
       [3.16915596e-08],
       [1.04862913e-07],
       [1.30044739e-08],
       [4.69881778e-09],
       [4.71971731e-07],
       [2.04128604e-02],
       [8.55446160e-06],
       [4.65026351e-05],
       [4.80176641e-05],
       [1.46666279e-08],
       [6.65747905e-07],
       [7.53336522e-08],
       [2.33834072e-07],
       [2.76601453e-09],
       [4.90153534e-03],
       [3.03510569e-06],
       [9.99934018e-01],
       [1.44315342e-08],
       [7.95910353e-07],
       [1.36826270e-06],
       [1.03326585e-07],
       [1.90770243e-06]], dtype=float32)

In [ ]:
y_test

173    0
274    1
491    0
72     0
452    0
      ..
412    0
436    0
411    0
86     0
75     0
Name: CAT. MEDV, Length: 102, dtype: int64

In [ ]:
for i in range(len(y_pred)):
  if(y_pred[i] > 0.5):
    y_pred[i] = 1
  else:
    y_pred[i] = 0

In [ ]:
y_pred

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
accuracy_score(y_test , y_pred)

0.9901960784313726